AWSTemplateFormatVersion: 2010-09-09
Resources:
  BackupServiceRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    Properties:
      RoleName: aws-quicksight-service-role1
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  BackupServicePolicy:
    Type: 'AWS::IAM::Policy'
    DeletionPolicy: Delete
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: 'states:StartExecution'
            Resource: '*'
      PolicyName: aws-quicksight-service-policy1
      Roles:
        - !Ref BackupServiceRole

  S3Bucket:
    Type: 'AWS::S3::Bucket'
      
